Repository nimblehq/flutter-templates, pull requests merged in 2021-09, with the labels that each got.

#11 [3] Setup flavors for iOS
  .gitignore
  README.md
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/production.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/staging.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
Labels: type : feature

#10 [3] Setup flavors for Android
  .env.sample
  .gitignore
  README.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/staging/res/values/strings.xml
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/production.xcscheme
  ios/Runner.xcodeproj/xcshareddata/xcschemes/staging.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature

#13 Bump version 0.1.0 (2)
  pubspec.yaml
Labels: type : chore, 0.1.0

#15 [#7] As a user, I can run unit test
  lib/api/api_service.dart
  lib/model/response/user_response.dart
  lib/repository/credential_repository.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/mocks/generate_mocks.mocks.dart
  test/repository/credential_repository_test.dart
  test/widget_test.dart
Labels: type : feature, 0.2.0

#18 [Chore] Update git templates and code reviewer list
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/story_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
Labels: type : chore

#16 [#5] As a user, I can load the image, video, font assets
  README.md
  assets/fonts/neuzeit.otf
  assets/images/nimble_logo.png
  lib/gen/assets.gen.dart
  lib/gen/fonts.gen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, 0.2.0

#17 [#6] As a user, I can have the application support multiple locales
  l10n.yaml
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, 0.2.0

#19 [#8] Setup integration test and dependencies
  README.md
  integration_test/my_home_page_test.dart
  integration_test/real_app_test.dart
  integration_test/utils/test_util.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test_driver/integration_test.dart
Labels: type : feature, 0.2.0

#22 Release v0.2.0 (3) to master
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/story_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  README.md
  assets/fonts/neuzeit.otf
  assets/images/nimble_logo.png
  integration_test/my_home_page_test.dart
  integration_test/real_app_test.dart
  integration_test/utils/test_util.dart
  l10n.yaml
  lib/api/api_service.dart
  lib/gen/assets.gen.dart
  lib/gen/fonts.gen.dart
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/model/response/user_response.dart
  lib/repository/credential_repository.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/mocks/generate_mocks.mocks.dart
  test/repository/credential_repository_test.dart
  test/widget_test.dart
  test_driver/integration_test.dart
Labels: type : release

#20 Bump version v0.3.0 (3) to develop
  pubspec.yaml
Labels: type : chore
