Repository nimblehq/flutter-templates, pull requests merged in 2022-06, with the labels that each got.

#84 [#60] As a developer, I can have a CD process to build and deploy the iOS app to App Store
  .template/.github/workflows/ios_deploy_to_app_store.yml
  .template/.github/workflows/ios_deploy_to_testflight.yml
  .template/ios/fastlane/Fastfile
  .template/ios/fastlane/Managers/DistributionManager.rb
Labels: type : feature

#85 [#57] Add wiki content for the available configs when setting up a new project from init script
  .github/wiki/Generating-A-Project.md
  README.md
Labels: feature-flag

#88 [CHORE] Bump version to 0.9.0
  .template/pubspec.yaml
Labels: type : chore

#87 Release 0.8.0 (9)
  .github/wiki/Generating-A-Project.md
  .template/.github/workflows/ios_deploy_to_app_store.yml
  .template/.github/workflows/ios_deploy_to_testflight.yml
  .template/ios/fastlane/Fastfile
  .template/ios/fastlane/Managers/DistributionManager.rb
  .template/pubspec.yaml
  README.md
  scripts/setup.py
  scripts/test.py
Labels: type : release

#91 [#89] Add base use cases
  .template/lib/usecases/base/base_use_case.dart
  .template/lib/usecases/base/use_case_result.dart
Labels: type : feature
