Repository nimblehq/flutter-templates, pull requests merged in 2022-03, with the labels that each got.

#41 [#34] Update SDK and dependencies
  pubspec.lock
  pubspec.yaml
Labels: type : chore

#45 [#30][#32] Setting up CI for the project
  .github/workflows/test.yml
  test/api/repository/credential_repository_test.dart
Labels: priority : high, type : feature

#54 [#53] Add lint rule to the template project
  analysis_options.yaml
  integration_test/my_home_page_test.dart
  lib/api/exception/network_exceptions.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/provider/dio_provider.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/credential_repository_test.dart
Labels: type : feature

#52 [#43] Add the config for auto renaming the `json_serializable` variable as a snake case when building the generated files
  Makefile
  build.yaml
  scripts/setup.py
Labels: type : feature

#62 Update the project's maintainers info
  .github/CODEOWNERS
Labels: type : chore

#65 Release 0.5.0 (6)
  .github/CODEOWNERS
  .github/workflows/test.yml
  Makefile
  analysis_options.yaml
  build.yaml
  integration_test/my_home_page_test.dart
  lib/api/exception/network_exceptions.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/provider/dio_provider.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  scripts/setup.py
  test/api/repository/credential_repository_test.dart
Labels: type : release

#67 Bump version v0.6.0 (7) for develop
  pubspec.yaml
Labels: type : chore
