Repository nimblehq/flutter-templates, pull requests merged in 2022-11, with the labels that each got.

#106 [#100] Check unauthorized error and create refresh token function
  .template/lib/di/interceptor/app_interceptor.dart
Labels: type : feature

#111 Release 1.2.0
  .template/lib/di/interceptor/app_interceptor.dart
  .template/pubspec.yaml
Labels: type : release

#112 [Chore] Bump version 1.3.0
  .template/pubspec.yaml
Labels: type : chore
