Repository nimblehq/flutter-templates, pull requests merged in 2022-07, with the labels that each got.

#90 [#21] Add codecov to the ci/cd pipeline of the project
  .gitignore
  .template/.github/workflows/test.yml
  .template/README.md
  .template/codecov.yml
Labels: type : chore

#92 Release 0.9.0 (10)
  .gitignore
  .template/.github/workflows/test.yml
  .template/README.md
  .template/codecov.yml
  .template/lib/usecases/base/base_use_case.dart
  .template/lib/usecases/base/use_case_result.dart
  .template/pubspec.yaml
Labels: type : release

#93 [CHORE] Bump version to 1.0.0
  .template/pubspec.yaml
Labels: type : chore

#98 [#96] Add go_router as a main navigator
  .template/integration_test/my_home_page_test.dart
  .template/integration_test/utils/test_util.dart
  .template/lib/main.dart
  .template/pubspec.lock
  .template/pubspec.yaml
Labels: type : feature

#99 [CHORE] Release 1.0.0
  .template/integration_test/my_home_page_test.dart
  .template/integration_test/utils/test_util.dart
  .template/lib/main.dart
  .template/pubspec.lock
  .template/pubspec.yaml
Labels: type : release
