Repository nimblehq/flutter-templates, pull requests merged in 2022-05, with the labels that each got.

#79 [#56] Fix test cases failed for init script
  Makefile
  scripts/setup.py
  scripts/test.py
Labels: priority : high, type : bug

#77 [#76] Add workflows for publishing docs to WIKI
  .github/wiki/Deployment.md
  .github/workflows/publish_docs_to_wiki.yml
Labels: type : feature

#80 [#64] As a developer, I can run the test for template in CI
  .github/CODEOWNERS
  .github/workflows/test.yml
  scripts/setup.py
Labels: type : feature

#75 [#59] [Part 1] As a developer, I can have a CD process to build and deploy the iOS app to TestFlight
  .template/.github/workflows/ios_deployment.yml
  .template/ios/.gitignore
  .template/ios/Gemfile
  .template/ios/Gemfile.lock
  .template/ios/Podfile
  .template/ios/Podfile.lock
  .template/ios/Runner.xcodeproj/project.pbxproj
  .template/ios/fastlane/Constants/Constants.rb
  .template/ios/fastlane/Constants/Environments.rb
  .template/ios/fastlane/Fastfile
  .template/ios/fastlane/Gymfile
  .template/ios/fastlane/Managers/BuildManager.rb
  .template/ios/fastlane/Managers/DistributionManager.rb
  .template/ios/fastlane/Managers/MatchManager.rb
  .template/ios/fastlane/Matchfile
Labels: type : feature

#78 [#59] [Part 2] As a developer, I can have a CD process to build and deploy the iOS app to TestFlight
  .github/wiki/Deployment.md
Labels: type : feature

#81 Release 0.7.0 (8)
  .github/CODEOWNERS
  .github/wiki/Deployment.md
  .github/workflows/publish_docs_to_wiki.yml
  .github/workflows/test.yml
  .template/.github/workflows/ios_deployment.yml
  .template/ios/.gitignore
  .template/ios/Gemfile
  .template/ios/Gemfile.lock
  .template/ios/Podfile
  .template/ios/Podfile.lock
  .template/ios/Runner.xcodeproj/project.pbxproj
  .template/ios/fastlane/Constants/Constants.rb
  .template/ios/fastlane/Constants/Environments.rb
  .template/ios/fastlane/Fastfile
  .template/ios/fastlane/Gymfile
  .template/ios/fastlane/Managers/BuildManager.rb
  .template/ios/fastlane/Managers/DistributionManager.rb
  .template/ios/fastlane/Managers/MatchManager.rb
  .template/ios/fastlane/Matchfile
  .template/pubspec.yaml
  Makefile
  scripts/setup.py
  scripts/test.py
Labels: type : release

#82 [CHORE] Bump version to 0.8.0
  .template/pubspec.yaml
Labels: type : chore

#83 [#49] Fix: Bundle identifier does not allow underscore in iOS
  scripts/setup.py
  scripts/test.py
Labels: type : bug
