Repository nimblehq/flutter-templates, pull requests merged in 2022-02, with the labels that each got.

#31 [#25] As a user, I have an option to initialize the app version when initializing new project
  Makefile
  README.md
  scripts/setup.py
  scripts/test.py
Labels: type : feature

#35 Release v0.4.0 (6)
  .env.sample
  .gitignore
  Makefile
  README.md
  android/app/build.gradle
  android/build.gradle
  lib/api/api_service.dart
  lib/api/exception/network_exceptions.dart
  lib/api/repository/credential_repository.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/provider/dio_provider.dart
  lib/env.dart
  lib/gen/assets.gen.dart
  lib/gen/fonts.gen.dart
  lib/model/response/user_response.dart
  pubspec.lock
  pubspec.yaml
  scripts/setup.py
  scripts/test.py
  test/api/repository/credential_repository_test.dart
  test/mocks/generate_mocks.dart
  test/mocks/generate_mocks.mocks.dart
  test/repository/credential_repository_test.dart
Labels: 0.4.0

#36 Bump v0.5.0 (6) for develop
  pubspec.yaml
Labels: priority: normal
