Repository nimblehq/flutter-templates, pull requests merged in 2023-07, with the labels that each got.

#203 [#160] [Generate project with Mason] Generate "permission handler" as an optional feature
  bricks/permission_handler/README.md
  bricks/permission_handler/__brick__/{{project_name.snakeCase()}}/lib/utils/wrappers/permission_wrapper.dart
  bricks/permission_handler/__brick__/{{~ _Podfile_build_configurations }}
  bricks/permission_handler/__brick__/{{~ _pubspec_dependency.yaml }}
  bricks/permission_handler/brick.yaml
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Podfile
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
  bricks/template/brick.yaml
  bricks/template/hooks/.gitignore
  bricks/template/hooks/bundles/permission_handler_bundle.dart
  bricks/template/hooks/post_gen.dart
  bricks/template/hooks/pre_gen.dart
  bricks/template/hooks/pubspec.lock
  bricks/template/hooks/pubspec.yaml
  mason-config.json
  mason.yaml
Labels: type : feature

#208 Release 1.9.0
  bricks/permission_handler/README.md
  bricks/permission_handler/__brick__/{{project_name.snakeCase()}}/lib/utils/wrappers/permission_wrapper.dart
  bricks/permission_handler/__brick__/{{~ _Podfile_build_configurations }}
  bricks/permission_handler/__brick__/{{~ _pubspec_dependency.yaml }}
  bricks/permission_handler/brick.yaml
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Podfile
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
  bricks/template/brick.yaml
  bricks/template/hooks/.gitignore
  bricks/template/hooks/bundles/permission_handler_bundle.dart
  bricks/template/hooks/post_gen.dart
  bricks/template/hooks/pre_gen.dart
  bricks/template/hooks/pubspec.lock
  bricks/template/hooks/pubspec.yaml
  mason-config.json
  mason.yaml
Labels: type : chore

#209 [Chore] Bump version to 1.10.0
  mason-config.json
Labels: type : chore

#211 [#210] Fix: generating sample project is failing to push changes to develop (protected branch)
  .github/workflows/generate_sample.yml
Labels: priority : high, type : bug

#213 [Chore] Improve: skip git push action if there are no changes from the sample project
  .github/workflows/generate_sample.yml
Labels: type : chore

#220 [#200] Fix: The new project generator with Mason removes all variable params with ${{ }} format in workflows
  .github/CODEOWNERS
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/CODEOWNERS
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production_to_playstore.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_staging.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/bump_version.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_staging_to_firebase.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_app_store.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_testflight.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/test.yml
Labels: type : bug

#201 [#197] Keep the template project up to date with new configurations, versions from the Flutter starter project
  .github/workflows/android_deploy_production.yml
  .github/workflows/android_deploy_production_to_playstore.yml
  .github/workflows/android_deploy_staging.yml
  .github/workflows/generate_sample.yml
  .github/workflows/ios_deploy_staging_to_firebase.yml
  .github/workflows/test.yml
  README.md
  bricks/permission_handler/__brick__/{{~ _pubspec_dependency.yaml }}
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE.md
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/PULL_REQUEST_TEMPLATE/release_template.md
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production_to_playstore.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_staging.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_staging_to_firebase.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_app_store.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_testflight.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/test.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.gitignore
  bricks/template/__brick__/{{project_name.snakeCase()}}/README.md
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/app/src/debug/AndroidManifest.xml
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/app/src/main/AndroidManifest.xml
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/app/src/main/res/values-night/styles.xml
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/app/src/main/res/values/styles.xml
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/app/src/profile/AndroidManifest.xml
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/build.gradle
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/gradle/wrapper/gradle-wrapper.properties
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/.gitignore
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Flutter/AppFrameworkInfo.plist
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Podfile
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Podfile.lock
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner.xcodeproj/project.pbxproj
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner.xcodeproj/xcshareddata/xcschemes/production.xcscheme
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner.xcodeproj/xcshareddata/xcschemes/staging.xcscheme
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner/Info.plist
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/RunnerTests/RunnerTests.swift
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/api/exception/network_exceptions.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/di/provider/dio_provider.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.lock
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
  bricks/template/hooks/bundles/permission_handler_bundle.dart
  bricks/template/hooks/pubspec.lock
Labels: type : chore

#231 [#224] Add support for SVG and color assets
  bricks/template/__brick__/{{project_name.snakeCase()}}/assets/colors/colors.xml
  bricks/template/__brick__/{{project_name.snakeCase()}}/assets/svg/flutter_logo.svg
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Podfile.lock
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/main.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.lock
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
Labels: type : feature

#240 [#197] Fix: Add missing iOS configurations + refactor Firebase env for app distributions
  .github/workflows/android_deploy_production.yml
  .github/workflows/android_deploy_staging.yml
  .github/workflows/ios_deploy_staging_to_firebase.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_staging.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_staging_to_firebase.yml
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/Runner.xcodeproj/project.pbxproj
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/fastlane/Constants/Constants.rb
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/fastlane/Constants/Environments.rb
  bricks/template/__brick__/{{project_name.snakeCase()}}/ios/fastlane/Fastfile
Labels: type : bug

#238 [#110] [#180] [#173] Add documentation for template supported features & components
  README.md
  bricks/template/__brick__/{{project_name.snakeCase()}}/README.md
  bricks/template/__brick__/{{project_name.snakeCase()}}/build.yaml
  bricks/template/__brick__/{{project_name.snakeCase()}}/codecov.yml
  sample/codecov.yml
Labels: type : chore

#244 [#223] Update the DI config & the base project structure with initial components
  README.md
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/api/api_service.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/api/repository/credential_repository.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/api/response/user_response.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/di/di.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/di/module/network_module.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/di/provider/dio_provider.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/home_view_model.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/home_view_state.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/main.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/model/user.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/lib/usecases/user/get_users_use_case.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.lock
  bricks/template/__brick__/{{project_name.snakeCase()}}/pubspec.yaml
  bricks/template/__brick__/{{project_name.snakeCase()}}/test/api/repository/credential_repository_test.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/test/mocks/generate_mocks.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/test/mocks/response/user_response_mocks.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/test/usecases/user/get_users_use_case_test.dart
  bricks/template/__brick__/{{project_name.snakeCase()}}/test/viewmodel/home_view_model_test.dart
Labels: type : feature

#247 [#222] Add new workflow to automate the mason bundle updating process after modifying the bundle config
  .github/workflows/test.yml
Labels: type : feature

#251 [#229] [Android] Add signing config for debug and release builds
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/.gitignore
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/config/debug.keystore
  bricks/template/__brick__/{{project_name.snakeCase()}}/android/signing.properties
Labels: type : feature
