Repository nimblehq/flutter-templates, pull requests merged in 2023-02, with the labels that each got.

#146 Release 1.4.0
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .github/workflows/test.yml
  .template/.github/workflows/test.yml
  .template/analysis_options.yaml
  .template/pubspec.yaml
  scripts/setup.py
Labels: type : chore

#147 [Chore] Bump version to 1.5.0
  .template/pubspec.yaml
Labels: type : chore

#148 [#139] Fix unit test command in README file
  .template/README.md
Labels: type : bug

#150 [#149] Add missing Flutter generated files to analysis_options exclusion config
  .template/analysis_options.yaml
Labels: type : feature

#151 [#138] Export MainActivity to support running on Android 12+
  .template/android/app/src/main/AndroidManifest.xml
Labels: type : bug
